/*
 * FlashCanvas Pro
 *
 * Copyright (c) 2009      Tim Cameron Ryan
 * Copyright (c) 2009-2011 Shinya Muramatsu
 */
window.ActiveXObject&&!window.CanvasRenderingContext2D&&function(l,k,r){function L(a){this.code=a;this.message=ea[a]}function s(a,b,c){if(!c)for(var c=[],d=0,e=a*b*4;d<e;++d)c[d]=0;this.width=a;this.height=b;this.data=c}function fa(a){this.width=a}function M(a){this.id=a.F++}function t(a){this.J=a;this.id=a.F++}function y(a,b){this.canvas=a;this.w=b;this.e=b.id.slice(8);this.G();this.F=0;this.j=this.D="";this.c=0}function z(){if(k.readyState==="complete"){k.detachEvent(N,z);for(var a=k.getElementsByTagName(p),
b=0,c=a.length;b<c;++b)A.initElement(a[b])}}function O(){var a=event.srcElement,b=a.parentNode;a.blur();b.focus()}function B(){event.button&2&&event.srcElement.parentNode.setCapture()}function C(){event.button&2&&event.srcElement.parentNode.releaseCapture()}function P(){var a=event.propertyName;if(a==="width"||a==="height"){var b=event.srcElement,c=b[a],d=parseInt(c,10);if(isNaN(d)||d<0)d=a==="width"?300:150;c===d?(b.style[a]=d+"px",b.getContext("2d").K(b.width,b.height)):b[a]=d}}function Q(){l.detachEvent(R,
Q);for(var a in j){var b=j[a],c=b.firstChild,d;for(d in c)typeof c[d]==="function"&&(c[d]=g);for(d in b)typeof b[d]==="function"&&(b[d]=g);c.detachEvent(S,O);c.detachEvent(D,B);b.detachEvent(E,C);b.detachEvent(T,P)}l[U]=g;l[V]=g;l[W]=g;l[F]=g;l[X]=g}function ga(a){return a.toLowerCase()}function i(a){throw new L(a);}function Y(a){var b=parseInt(a.width,10),c=parseInt(a.height,10);if(isNaN(b)||b<0)b=300;if(isNaN(c)||c<0)c=150;a.width=b;a.height=c}function G(a,b){for(var c in j){var d=j[c].getContext("2d");
d.g.push(d.a.length+2);d.a.push(u,a,b)}}var g=null,p="canvas",U="CanvasRenderingContext2D",V="CanvasGradient",W="CanvasPattern",F="FlashCanvas",X="G_vmlCanvasManager",S="onfocus",D="onmousedown",E="onmouseup",T="onpropertychange",N="onreadystatechange",R="onunload",m;try{m=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").match(/[\d,]+/)[0].replace(/,/g,".")}catch(ja){m=0}var n=l[F+"Options"]||{},ha=function(){var a=k.getElementsByTagName("script"),a=a[a.length-1];return k.documentMode>=
8?a.src:a.getAttribute("src",4)}().replace(/[^\/]+$/,""),o=n.swfPath||ha;o+=parseInt(m)>9?"flash10canvas.swf":"flash9canvas.swf";var u="4",v={},w={},Z={},H={},q={},$={},j={},x={},I="turbo"in n?n.turbo:1,J=n.delay||0,aa=n.disableContextMenu||0,ba=n.imageCacheSize||100,K=n.usePolicyFile||0,ca=n.proxy||"proxy.php",da=n.save||"save.php";m==="10.1.53.64"&&(I=0,J=30);y.prototype={save:function(){this.f(15);this.I.push([this.l,this.m,this.v,this.k,this.p,this.n,this.o,this.q,this.t,this.u,this.r,this.s,
this.j,this.z,this.A]);this.a.push("B")},restore:function(){var a=this.I;if(a.length)a=a.pop(),this.globalAlpha=a[0],this.globalCompositeOperation=a[1],this.strokeStyle=a[2],this.fillStyle=a[3],this.lineWidth=a[4],this.lineCap=a[5],this.lineJoin=a[6],this.miterLimit=a[7],this.shadowOffsetX=a[8],this.shadowOffsetY=a[9],this.shadowBlur=a[10],this.shadowColor=a[11],this.font=a[12],this.textAlign=a[13],this.textBaseline=a[14];this.a.push("C")},scale:function(a,b){this.a.push("D",a,b)},rotate:function(a){this.a.push("E",
a)},translate:function(a,b){this.a.push("F",a,b)},transform:function(a,b,c,d,e,f){this.a.push("G",a,b,c,d,e,f)},setTransform:function(a,b,c,d,e,f){this.a.push("H",a,b,c,d,e,f)},createLinearGradient:function(a,b,c,d){(!isFinite(a)||!isFinite(b)||!isFinite(c)||!isFinite(d))&&i(9);this.a.push("M",a,b,c,d);return new t(this)},createRadialGradient:function(a,b,c,d,e,f){(!isFinite(a)||!isFinite(b)||!isFinite(c)||!isFinite(d)||!isFinite(e)||!isFinite(f))&&i(9);(c<0||f<0)&&i(1);this.a.push("N",a,b,c,d,e,
f);return new t(this)},createPattern:function(a,b){a||i(17);var c=a.tagName,d,e,f,h=this.e;if(c)if(c=c.toLowerCase(),c==="img")d=a.getAttribute("src",2);else if(c===p)e=this.C(a),f=a!==this.canvas;else if(c==="video")return;else i(17);else a.src?d=a.src:i(17);b==="repeat"||b==="no-repeat"||b==="repeat-x"||b==="repeat-y"||b===""||b===g||i(12);e||(e=w[h][d],(f=e===r)&&(e=this.B(d)));this.a.push("O",e,b);f&&v[h]&&(this.h(),++q[h]);return new M(this)},clearRect:function(a,b,c,d){this.a.push("X",a,b,c,
d);this.b||this.d();this.c=0},fillRect:function(a,b,c,d){this.f(1);this.a.push("Y",a,b,c,d);this.b||this.d();this.c=0},strokeRect:function(a,b,c,d){this.f(6);this.a.push("Z",a,b,c,d);this.b||this.d();this.c=0},beginPath:function(){this.a.push("a")},closePath:function(){this.a.push("b")},moveTo:function(a,b){this.a.push("c",a,b)},lineTo:function(a,b){this.a.push("d",a,b)},quadraticCurveTo:function(a,b,c,d){this.a.push("e",a,b,c,d)},bezierCurveTo:function(a,b,c,d,e,f){this.a.push("f",a,b,c,d,e,f)},
arcTo:function(a,b,c,d,e){e<0&&isFinite(e)&&i(1);this.a.push("g",a,b,c,d,e)},rect:function(a,b,c,d){this.a.push("h",a,b,c,d)},arc:function(a,b,c,d,e,f){c<0&&isFinite(c)&&i(1);this.a.push("i",a,b,c,d,e,f?1:0)},fill:function(){this.f(1);this.a.push("j");this.b||this.d();this.c=0},stroke:function(){this.f(6);this.a.push("k");this.b||this.d();this.c=0},clip:function(){this.a.push("l")},isPointInPath:function(a,b){this.a.push("m",a,b);return this.h()==="true"},fillText:function(a,b,c,d){this.f(9);this.g.push(this.a.length+
1);this.a.push("r",a,b,c,d===r?Infinity:d);this.b||this.d();this.c=0},strokeText:function(a,b,c,d){this.f(10);this.g.push(this.a.length+1);this.a.push("s",a,b,c,d===r?Infinity:d);this.b||this.d();this.c=0},measureText:function(a){var b=x[this.e];try{b.style.font=this.font}catch(c){}b.innerText=a.replace(/[ \n\f\r]/g,"\t");return new fa(b.offsetWidth)},drawImage:function(a,b,c,d,e,f,h,ia,l){a||i(17);var g=a.tagName,k,j,n,m=arguments.length,o=this.e;if(g)if(g=g.toLowerCase(),g==="img")k=a.getAttribute("src",
2);else if(g===p)j=this.C(a),n=a!==this.canvas;else if(g==="video")return;else i(17);else a.src?k=a.src:i(17);j||(j=w[o][k],(n=j===r)&&(j=this.B(k)));this.f(0);if(m===3)this.a.push("u",m,j,b,c);else if(m===5)this.a.push("u",m,j,b,c,d,e);else if(m===9)(d===0||e===0)&&i(1),this.a.push("u",m,j,b,c,d,e,f,h,ia,l);else return;n&&v[o]?(this.h(),++q[o]):this.b||this.d();this.c=0},createImageData:function(a,b){var c=Math.ceil;arguments.length===2?((!isFinite(a)||!isFinite(b))&&i(9),(a===0||b===0)&&i(1)):(a instanceof
s||i(9),b=a.height,a=a.width);a=c(a<0?-a:a);b=c(b<0?-b:b);return new s(a,b)},getImageData:function(a,b,c,d){(!isFinite(a)||!isFinite(b)||!isFinite(c)||!isFinite(d))&&i(9);(c===0||d===0)&&i(1);this.a.push("w",a,b,c,d);a=this.h();c=typeof JSON==="object"?JSON.parse(a):k.documentMode?eval(a):a.slice(1,-1).split(",");a=c.shift();b=c.shift();return new s(a,b,c)},putImageData:function(a,b,c,d,e,f,h){a instanceof s||i(17);(!isFinite(b)||!isFinite(c))&&i(9);var g=arguments.length,j=a.width,k=a.height,l=a.data;
g===3?this.a.push("x",g,j,k,l.toString(),b,c):g===7&&((!isFinite(d)||!isFinite(e)||!isFinite(f)||!isFinite(h))&&i(9),this.a.push("x",g,j,k,l.toString(),b,c,d,e,f,h));this.b||this.d();this.c=0},loadImage:function(a){this.drawImage(a,-1E5,-1E5)},G:function(){this.globalAlpha=this.l=1;this.globalCompositeOperation=this.m="source-over";this.fillStyle=this.k=this.strokeStyle=this.v="#000000";this.lineWidth=this.p=1;this.lineCap=this.n="butt";this.lineJoin=this.o="miter";this.miterLimit=this.q=10;this.shadowBlur=
this.r=this.shadowOffsetY=this.u=this.shadowOffsetX=this.t=0;this.shadowColor=this.s="rgba(0, 0, 0, 0.0)";this.font=this.j="10px sans-serif";this.textAlign=this.z="start";this.textBaseline=this.A="alphabetic";this.a=[];this.I=[];this.i=[];this.g=[];this.b=g;this.H=1},f:function(a){var b=this.a,c;if(this.l!==this.globalAlpha)b.push("I",this.l=this.globalAlpha);if(this.m!==this.globalCompositeOperation)b.push("J",this.m=this.globalCompositeOperation);if(this.t!==this.shadowOffsetX)b.push("T",this.t=
this.shadowOffsetX);if(this.u!==this.shadowOffsetY)b.push("U",this.u=this.shadowOffsetY);if(this.r!==this.shadowBlur)b.push("V",this.r=this.shadowBlur);if(this.s!==this.shadowColor)c=this.s=this.shadowColor,(""+c).indexOf("%")>0&&this.i.push(b.length+1),b.push("W",c);if(a&1&&this.k!==this.fillStyle)c=this.k=this.fillStyle,typeof c==="object"?c=c.id:(""+c).indexOf("%")>0&&this.i.push(b.length+1),b.push("L",c);if(a&2&&this.v!==this.strokeStyle)c=this.v=this.strokeStyle,typeof c==="object"?c=c.id:(""+
c).indexOf("%")>0&&this.i.push(b.length+1),b.push("K",c);if(a&4){if(this.p!==this.lineWidth)b.push("P",this.p=this.lineWidth);if(this.n!==this.lineCap)b.push("Q",this.n=this.lineCap);if(this.o!==this.lineJoin)b.push("R",this.o=this.lineJoin);if(this.q!==this.miterLimit)b.push("S",this.q=this.miterLimit)}if(a&8){if(this.j!==this.font)a=x[this.e].offsetHeight,this.g.push(b.length+2),b.push("o",a,this.j=this.font);if(this.z!==this.textAlign)b.push("p",this.z=this.textAlign);if(this.A!==this.textBaseline)b.push("q",
this.A=this.textBaseline);if(this.D!==this.canvas.currentStyle.direction)b.push("1",this.D=this.canvas.currentStyle.direction)}},d:function(){var a=this;a.b=setTimeout(function(){q[a.e]?a.d():(a.b=g,a.h(I))},J)},L:function(){clearTimeout(this.b);this.b=g},h:function(a){var b,c,d,e=this.i,f=this.g,h=this.a,g=this.w;if(h.length){this.b&&this.L();if(a){for(b=0,c=e.length;b<c;++b)d=e[b],h[d]=encodeURI(h[d]);for(b=0,c=f.length;b<c;++b)d=f[b],h[d]=encodeURIComponent(h[d])}else for(b=0,c=f.length;b<c;++b)d=
f[b],h[d]=(""+h[d]).replace(/&/g,"&amp;").replace(/</g,"&lt;");b=h.join("\u0001");this.a=[];this.i=[];this.g=[];if(a)g.flashvars="c="+b,g.width=g.clientWidth+this.H,this.H^=-2;else return g.CallFunction('<invoke name="executeCommand" returntype="javascript"><arguments><string>'+b+"</string></arguments></invoke>")}},K:function(a,b){this.h();this.G();if(a>0)this.w.width=a;if(b>0)this.w.height=b;this.a.push("2",a,b);this.b||this.d();this.c=0},C:function(a){var b=a.getContext("2d").e,c=p+":"+b;(a.width===
0||a.height===0)&&i(11);if(b!==this.e&&(a=j[b].getContext("2d"),!a.c))b=++$[b],c+=":"+b,a.a.push("3",b),a.b||a.d(),a.c=1;return c},B:function(a){var b=this.e,c=w[b],d=Z[b],e=c[a]=H[b]++;e>=ba-1&&(H[b]=0);e in d&&delete c[d[e]];this.g.push(this.a.length+2);this.a.push("5",e,a);d[e]=a;return e}};t.prototype={addColorStop:function(a,b){(isNaN(a)||a<0||a>1)&&i(1);var c=this.J,d=this.id;(""+b).indexOf("%")>0&&c.i.push(c.a.length+3);c.a.push("y",d,a,b)}};L.prototype=Error();var ea={1:"INDEX_SIZE_ERR",9:"NOT_SUPPORTED_ERR",
11:"INVALID_STATE_ERR",12:"SYNTAX_ERR",17:"TYPE_MISMATCH_ERR",18:"SECURITY_ERR"},A={initElement:function(a){if(a.getContext)return a;var b=Math.random().toString(36).slice(2)||"0",c="external"+b;v[b]=0;w[b]={};Z[b]=[];H[b]=0;q[b]=1;$[b]=0;Y(a);a.innerHTML='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="'+location.protocol+'//fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="100%" height="100%" id="'+c+'"><param name="allowScriptAccess" value="always"><param name="flashvars" value="id='+
c+'"><param name="wmode" value="transparent"></object><span style="margin:0;padding:0;border:0;display:inline-block;position:static;height:1em;overflow:visible;white-space:nowrap"></span>';j[b]=a;var d=a.firstChild;x[b]=a.lastChild;var e=k.body.contains;if(e(a))d.movie=o;else var f=setInterval(function(){if(e(a))clearInterval(f),d.movie=o},0);if(k.compatMode==="BackCompat"||!l.XMLHttpRequest)x[b].style.overflow="hidden";var h=new y(a,d);a.getContext=function(a){return a==="2d"?h:g};a.toDataURL=function(b,
c){if(a.width===0||a.height===0)return"data:,";(""+b).replace(/[A-Z]+/g,ga)==="image/jpeg"?h.a.push("A",b,typeof c==="number"?c:""):h.a.push("A",b);return h.h().slice(1,-1)};d.attachEvent(S,O);aa&&(d.attachEvent(D,B),a.attachEvent(E,C));K&&h.a.push(u,"usePolicyFile",K);b=h.a.length;h.g.push(b+2,b+5);h.a.push(u,"proxy",ca,u,"save",da);return a},saveImage:function(a){a.firstChild.saveImage()},setOptions:function(a){for(var b in a){var c=a[b];switch(b){case "turbo":I=c;break;case "delay":J=c;break;case "disableContextMenu":aa=
c;var d=void 0;for(d in j){var e=j[d],f=c?"attachEvent":"detachEvent";e.firstChild[f](D,B);e[f](E,C)}break;case "imageCacheSize":ba=c;break;case "usePolicyFile":G(b,K=c?1:0);break;case "proxy":G(b,ca=c);break;case "save":G(b,da=c)}}},trigger:function(a,b){j[a].fireEvent("on"+b)},unlock:function(a,b){q[a]&&--q[a];if(b){var c=j[a],d=c.firstChild,e,f;Y(c);e=c.width;f=c.height;c.style.width=e+"px";c.style.height=f+"px";if(e>0)d.width=e;if(f>0)d.height=f;d.resize(e,f);c.attachEvent(T,P);v[a]=1;typeof c.onload===
"function"&&setTimeout(function(){c.onload()},0)}}};k.createElement(p);k.createStyleSheet().cssText=p+"{display:inline-block;overflow:hidden;width:300px;height:150px}";k.readyState==="complete"?z():k.attachEvent(N,z);l.attachEvent(R,Q);o.indexOf(location.protocol+"//"+location.host+"/")===0&&(m=new ActiveXObject("Microsoft.XMLHTTP"),m.open("GET",o,!1),m.send(g));l[U]=y;l[V]=t;l[W]=M;l[F]=A;l[X]={init:function(){},init_:function(){},initElement:A.initElement}}(window,document);
